version: '3.4'

services:
  php-apache-environment:
    image: nursukma/php
    container_name: php-apache
    depends_on:
      - db
    volumes:
      - ./php/
    ports:
      - 80:80
    networks:
      - backend
    
  db:
    container_name: db
    image: mysql
    restar: always
    environment:
      - MYSQL_ROOT_PASSWORD: root
      - MYSQL_DATABASE: resepsionis
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
      - ./php_resepsionis.sql:/docker-entrypoint-intdb.d/php_resepsionis.sql
    networks:
      - backend

volumes:
  db:

networks:
  backend:
